language: julia
julia:
  - 1.0
  - 1.1
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install matplotlib
  - julia --color=yes -e 'import Pkg; Pkg.add("PyCall")'
  - julia --color=yes -e 'import Pkg; ENV["PYTHON"]="python"; Pkg.build("PyCall")'

after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()
