language: julia
julia:
  - 1.0
  - 1.1
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install matplotlib
  - julia -e "using Pkg; Pkg.add("PyCall")"
  - julia -e "using Pkg; ENV[PYTHON]="python"; Pkg.build("PyCall")"
